version: '3.8'

services:
  php:
    build:
      context: docker/php
    working_dir: /app
    environment:
      - PHP_IDE_CONFIG=serverName=docker
    volumes:
      - .:/app
      - ./docker/php/config/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini:ro
